impl Default for AddressSpace to make future changes easier
TheDan64/inkwell pull request #385
Opened 2022-12-18 14:51 UTC by folkertdev

in #383 it came up that the current representation of an address space is not entirely correct. To make changes to that type easier, and because usually "Generic" is the address space that users want, implementing and using the default instance means that even if we change the representation of address spaces, this would not actually be noticeable by users.

## Description

## Related Issue

## How This Has Been Tested

## \<Breaking Changes\>

There specifically are no breaking changes in the PR

## Checklist

- [x] I have read the [Contributing Guide](https://github.com/TheDan64/inkwell/blob/master/.github/CONTRIBUTING.md)

2022-12-18 14:52 UTC, folkertdev commented
cc @hedgar2017

2022-12-18 15:07 UTC, hedgar2017 commented
@folkertdev I think we must remove this enum completely and use u32 instead.

2022-12-18 15:09 UTC, hedgar2017 commented
@folkertdev each target has its own understanding and treatment of address spaces. For example for our virtual machine it's:
0 - stack
1 - the 1st heap
2 - the 2nd heap
3 - arbitrary memory page
4 - the space of constants
and so on.

Some targets may use a large number of address spaces, so someone will eventually be blocked by this enum anyway.

2022-12-18 15:11 UTC, hedgar2017 requested changes
Let's remove the enum?
It's already casted to u32 everywhere.

2022-12-18 15:15 UTC, folkertdev commented
I understand that you want to change the representation. That is however breaking for pretty much every user of inkwell. so this PR would be a step towards making that process easier, because usually you want to use the default address space.

Anyway, I don't know exactly what the policy is on breaking changes, that is ultimately up to @TheDan64 to decide. This PR is safe to merge no matter what, since it is strictly additive.

2022-12-18 15:29 UTC, hedgar2017 commented
@folkertdev I understand, but it's not a good reason to stockpile such blocking and misleading technical debt.

Concerning this patch, adding this default may be reasonable for your particular target, but for a lot of other targets the 0-th address space is not more default than others.

2022-12-18 15:41 UTC, folkertdev commented
well, https://llvm-swift.github.io/LLVMSwift/Structs/AddressSpace.html says

> An address space is an identifier for a target-specific range of address values. An address space is a fundamental part of the type of a pointer value and the type of operations that manipulate memory.
> 
> LLVM affords a default address space (numbered zero) and places a number of assumptions on pointer values within that address space:
> 
> - The pointer must have a fixed integral value
> - The null pointer has a bit-value of 0

so out of all the address spaces, I think `0` is objectively the most default. For common targets, it is also probably the only one you'll ever use

2022-12-18 15:52 UTC, hedgar2017 commented
@folkertdev well, you're right, I indeed found this in the official doc.
It's up to @TheDan64 of course.

2022-12-18 17:59 UTC, hedgar2017 approved these changes

2022-12-19 02:25 UTC, TheDan64 commented
Has anyone confirmed 5+ are valid values LLVM accepts for address spaces?

2022-12-19 02:31 UTC, TheDan64 commented
I'm ok with converting to a u32 if so

2022-12-19 09:40 UTC, folkertdev commented
well, it turns out that the address space is really as 24-bit integer. in other words, this test passes 

```rust
#[test]
fn test_ptr_address_space() {
    let context = Context::create();

    let spaces = [0, 1, 2, 3, 4, 5, 6, 1 << 24 - 1];

    for index in spaces {
        let address_space = AddressSpace(index);

        let ptr = context.i32_type().ptr_type(address_space);
        assert_eq!(ptr.get_address_space(), address_space);
    }

    let address_space = AddressSpace(1 << 24);
    let ptr = context.i32_type().ptr_type(address_space);
    assert_ne!(ptr.get_address_space(), address_space);
}
```

Not sure what to do with that. We could pick `u16` internally, and assume that is good enough (really how many address spaces can you use in practice). Using `u32` is incorrect I think and using it would not align with Inkwell's goals.

2022-12-19 10:47 UTC, hedgar2017 commented
@folkertdev thanks for checking! By the way, we can use `2^24 - 1` address spaces in practice. If you don't use them, it doesn't mean that nobody else needs it.

I propose we make some kind of `AddressSpace(u32)` wrapper with an assertion in the constructor that it's not bigger than `2^24 - 1`. This way we'll fully cover the functionality LLVM provides and still keep it safe and ugly-low-level-crash-free.

2022-12-19 10:50 UTC, hedgar2017 requested changes
Oh, thanks a lot for this change.
Please encapsulate the inner value with an `address_space < 2^24` assertion and I believe it's ready for merging!

2022-12-19 14:07 UTC, hedgar2017 requested changes

2022-12-19 14:07 UTC, hedgar2017 commented on src/lib.rs
> +    pub const FIVE: Self = Self(5);
These constants are probably redundant. Do you need them?

2022-12-19 14:22 UTC, hedgar2017 commented on src/lib.rs
> +    pub const FIVE: Self = Self(5);
Another alternative is not using magic numbers and having an enum in your own front-end with proper descriptive names for each address space.
`inkwell::AddressSpace::try_from(crate::AddressSpace::Stack)?` is not ugly.

2022-12-19 14:26 UTC, hedgar2017 requested changes
I believe we should remove the constants, because their names are not descriptive like @folkertdev himself said a while ago.
The inkwell users must define their AddressSpace logic outside of this crate.

2022-12-19 14:41 UTC, folkertdev commented
I disagree. you would force functions upon your users that look like they can panic, but they actually can't. That is disappointing API design.

2022-12-19 14:48 UTC, hedgar2017 commented
I didn't get what the constants had to do with panics.
No big deal for me, it's up to @TheDan64

2022-12-19 23:13 UTC, folkertdev commented
added an instance for `From<u16>` (that means `::from(3)` works and is not ambiguous. `u8` can always (and conveniently) be upcast to `u16`, and removed the constants.

2022-12-20 08:00 UTC, hedgar2017 commented
@folkertdev has your commit passed through? I see the last one 21h ago.

2022-12-20 13:05 UTC, folkertdev commented
should be good now, I think this is ready.

2022-12-20 18:07 UTC, hedgar2017 approved these changes

2022-12-21 08:16 UTC, TheDan64 approved these changes
Thanks!

2022-12-21 08:16 UTC, merged